Lint/AssignmentInCondition:
  Exclude:
    - 'bin/xcpretty'

Layout/DefEndAlignment:
  Enabled: true
  Exclude:
    - 'lib/xcpretty/formatters/formatter.rb'

Layout/EndAlignment:
  Enabled: true

Security/Eval:
  Exclude:
    - 'lib/xcpretty.rb'

Lint/FormatParameterMismatch:
  Exclude:
    - 'lib/xcpretty/formatters/simple.rb'

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'bin/xcpretty'
    - 'spec/**/*.rb'
    - 'features/**/*.rb'
    - 'lib/xcpretty/parser.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Count:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Layout/AlignHash:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Layout/AlignParameters:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: true

# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Layout/CaseIndentation:
  Enabled: true

Style/ClassVars:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerBackticks.
Style/CommandLiteral:
  Exclude:
    - 'features/support/*.rb'

Layout/CommentIndentation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'lib/xcpretty/ansi.rb'
    - 'lib/xcpretty/formatters/formatter.rb'

Layout/EmptyLineBetweenDefs:
  Exclude:
    - 'lib/xcpretty/formatters/formatter.rb'

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true
  Exclude:
    - 'lib/xcpretty/formatters/formatter.rb'

Layout/FirstParameterIndentation:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationWidth:
  Exclude:
    - 'spec/**/*.rb'

Layout/LeadingCommentSpace:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantBegin:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/Semicolon:
  Exclude:
    - 'bin/xcpretty'

Style/SignalException:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - 'lib/xcpretty/formatters/formatter.rb'

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideParens:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: true
  EnforcedStyle: final_blank_line

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/UnneededPercentQ:
  Exclude:
    - 'spec/**/*.rb'
    - 'xcpretty.gemspec'
